# Generated by Django 3.2 on 2022-09-30 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=40, null=True)),
                ('familyName', models.CharField(blank=True, max_length=40, null=True)),
                ('portfolioName', models.CharField(blank=True, max_length=40, null=True)),
                ('emailId', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tenure', models.IntegerField(default=0)),
                ('stock_data', models.JSONField(blank=True, default=list)),
                ('is_merged', models.BooleanField(default=False)),
                ('description', models.CharField(default='Portfolio', max_length=1000)),
                ('avg_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_risk', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sharpe_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_aum', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_model', models.BooleanField(default=False)),
                ('is_scratch', models.BooleanField(default=True)),
                ('weights', models.JSONField(blank=True, default=list)),
                ('model_type', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfoliodetails')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.serviceprice')),
            ],
        ),
        migrations.CreateModel(
            name='BuySellSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_signals', models.JSONField(blank=True, default=list)),
                ('sell_signal', models.JSONField(blank=True, default=list)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfoliodetails')),
            ],
        ),
    ]
