# Generated by Django 3.2 on 2022-12-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service',
        ),
        migrations.DeleteModel(
            name='BuySellSignals',
        ),
        migrations.DeleteModel(
            name='ServicePrice',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
