# Generated by Django 3.2 on 2023-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20221205_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliodetails',
            old_name='weights',
            new_name='risky_weights',
        ),
        migrations.AddField(
            model_name='portfoliodetails',
            name='stable_weights',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
